version: '3.8'  # specify docker-compose version

services:
  postgres:
    image: postgres:latest  # use the latest official postgres image
    container_name: postgres_db
    restart: always  # ensure the container restarts automatically if it crashes
    environment:
      POSTGRES_USER: admin  # change this to your desired username
      POSTGRES_PASSWORD: '12345'  # change this to your desired password
      POSTGRES_DB: users_history_prod  # change this to your desired database name
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persistent storage for database data
    ports:
      - "5432:5432"  # expose postgres port to the host

  nodejs-app:
    build:
      context: .  # the current directory (should contain your Dockerfile)
      dockerfile: Dockerfile  # Dockerfile to build the Node.js app
    container_name: user_history_be
    restart: always  # ensure the container restarts automatically if it crashes
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"  # expose the Node.js app on port 3000
    depends_on:
      - postgres  # ensure postgres starts before the Node.js app

volumes:
  postgres_data:
    driver: local  # store the data locally on the host